### ISSUE TITLE
Список преподавателей

### ISSUE THREAD

**Issue by jskonst** [ISUCT/keymaster#3]
## Task description
Как администратор я хочу видеть список преподавателей и соответствующие им идентификаторы карточек (id, ФИО, Номер карточки ) 

## Implementation details
Для реализации граяического интерфеса следует использовать - Material UI и компонента dataGrid
https://material-ui.com/ru/components/data-grid/

### Affected areas
Frontend only

Формат записей
```json
{
"id": "number", 
"fullName": "string",
"personalKey": "string"
}
```
Данные захардкожены на стороне UI

**Comment by SoldatovMikhaul** [comment]
![image](https://user-images.githubusercontent.com/55295303/121552983-90f68400-ca19-11eb-9fb5-fe797f774442.png)
